In [1]:
import pandas as pd

In [2]:
import requests, json
from pprint import pprint

In [10]:
# Get League ranking Data for all FPL Managers in the league
r = requests.get('https://fantasy.premierleague.com/api/leagues-classic/1/standings/?page_standings=1').json()

In [11]:
pprint(r)

{'last_updated_data': '2021-11-07T19:55:40Z',
 'league': {'admin_entry': None,
            'closed': False,
            'code_privacy': 'p',
            'created': '2021-06-22T10:37:32.859343Z',
            'cup_league': None,
            'has_cup': False,
            'id': 1,
            'league_type': 's',
            'max_entries': None,
            'name': 'Arsenal',
            'rank': None,
            'scoring': 'c',
            'start_event': 1},
 'new_entries': {'has_next': False, 'page': 1, 'results': []},
 'standings': {'has_next': True,
               'page': 1,
               'results': [{'entry': 706,
                            'entry_name': 'XI',
                            'event_total': 104,
                            'id': 2757,
                            'last_rank': 38,
                            'player_name': 'Oscar FPLF',
                            'rank': 1,
                            'rank_sort': 1,
                            'total': 847},
             

In [12]:
df_standings = pd.DataFrame(r['standings']['results'])

In [13]:
df_standings

id  event_total                player_name  rank  last_rank  \
0       2757          104                 Oscar FPLF     1         38   
1   42253151          112            Shayan Merchant     2        231   
2   44856175           86                  Don Donde     3         13   
3   46328273           92               Allister Ash     4         47   
4   10473968           74            Cameron Burdass     5          4   
5    9804664           65            Ryan Agalawatta     6          1   
6   40234572           68              Sani Siddiqui     7          2   
7   15804452           96               Gavin Dalton     7        130   
8   38696085           69          Marek Buszkiewicz     9          5   
9    4424129           81             William Bishop    10         36   
10   1180764           69               David Armani    11          8   
11   8515512           68              Safawi Zainal    11          6   
12  21105973           82             Tumelo Palweni    11         47   
13  25621885           64                Harry Singh    14          3   
14   9176946           72            Liam Fitzgerald    15         16   
15   3593787           72         James Angelopoulos    16         17   
16   1244710           69                Alex Rapala    16         11   
17      2060           69  Daniel Bradley (FPL Mate)    18         12   
18  26549709           71              Ibrahim Azhar    19         18   
19  46152303           78             Ackshaye Odoye    20         32   
20   4544561           70             Galih Erlangga    21         18   
21  33544878           70                     Vk Pai    22         26   
22  13511894           81                Ian Gorsuch    22         82   
23   1948641           69               Jak Attfield    24         23   
24  23693607           66            Gregor Gasparac    25         14   
25   5073003           70              Leon Nicholas    25         29   
26   6161729           63    Luca Pesce (Finesseeee)    27          9   
27   1121535           63               Great Oriahi    28         10   
28  37903615           70                Adamm Mzlan    29         30   
29  23685071           76             Ewen Alexander    30         65   
30   3720286           97         Andrew Wood-Martin    31        466   
31  35170592           70             Ayodeji Toyobo    32         34   
32  35596116           69       Amith Hariharasudhan    33         31   
33   3375033           75               Sachin Patel    34         70   
34  40352552           86                   Dosh Man    34        206   
35      3124           98            Martin Fazovski    36        604   
36  46232736           70               Alexx Allert    37         37   
37  26985375           62            Motti Orenstein    38          7   
38  35832764           73              Joshua Ramsay    39         70   
39   1792439           63                  Ewan Wood    40         18   
40    260362           70           Andreas Olofsson    40         47   
41  14095102           90              Saurabh Nagar    40        364   
42  12510995           69                Lizan Ahmed    43         41   
43     16811           69              Apurva Subedi    44         42   
44  32341628           69              Naufal Othman    45         44   
45  29278346           79                      Lee N    46        142   
46  36894527           70            Javan Robertson    47         56   
47  15474534           78             Pranav Prathap    48        128   
48   4816927           69              Tamir Pardess    49         47   
49  22052850           62           Charlie O'Connor    49         18   

    rank_sort  total    entry            entry_name  
0           1    847      706                    XI  
1           2    839  6023187            Invader_FC  
2           3    837  6340113             ITS DONDE  
3           4    834  6521337        Last Minute FC  
4           5   

In [212]:
# Get the players picked by a FPL Manager
r = requests.get('https://fantasy.premierleague.com/api/entry/2757/event/3/picks/').json()
r

{'active_chip': None,
 'automatic_subs': [],
 'entry_history': {'event': 3,
  'points': 77,
  'total_points': 240,
  'rank': 203220,
  'rank_sort': 203230,
  'overall_rank': 267693,
  'bank': 2,
  'value': 1012,
  'event_transfers': 2,
  'event_transfers_cost': 0,
  'points_on_bench': 5},
 'picks': [{'element': 30,
   'position': 1,
   'multiplier': 1,
   'is_captain': False,
   'is_vice_captain': False},
  {'element': 237,
   'position': 2,
   'multiplier': 1,
   'is_captain': False,
   'is_vice_captain': False},
  {'element': 418,
   'position': 3,
   'multiplier': 1,
   'is_captain': False,
   'is_vice_captain': False},
  {'element': 275,
   'position': 4,
   'multiplier': 1,
   'is_captain': False,
   'is_vice_captain': False},
  {'element': 359,
   'position': 5,
   'multiplier': 2,
   'is_captain': True,
   'is_vice_captain': False},
  {'element': 233,
   'position': 6,
   'multiplier': 1,
   'is_captain': False,
   'is_vice_captain': False},
  {'element': 419,
   'position': 7,


In [159]:
# Get the players picked by a FPL Manager each week

player_ids = []

for i in range(1,12):
    r = requests.get('https://fantasy.premierleague.com/api/entry/2757/event/'+str(i)+'/picks/').json()
    player_ids.append([x['element'] for x in r['picks']])
    
player_ids

[[30, 275, 418, 237, 233, 215, 289, 485, 413, 337, 177, 376, 245, 208, 145],
 [30, 275, 245, 237, 233, 215, 289, 485, 413, 337, 177, 376, 418, 208, 145],
 [30, 237, 418, 275, 359, 233, 419, 289, 413, 337, 177, 376, 208, 145, 245],
 [69, 237, 418, 275, 196, 233, 419, 289, 413, 579, 177, 376, 145, 208, 245],
 [69, 275, 418, 245, 145, 289, 196, 233, 419, 189, 579, 376, 413, 208, 237],
 [69, 237, 418, 275, 196, 233, 289, 419, 413, 579, 307, 376, 145, 245, 208],
 [69, 127, 418, 122, 196, 233, 289, 419, 413, 579, 307, 376, 145, 245, 208],
 [69, 208, 119, 256, 419, 289, 196, 233, 307, 413, 579, 376, 418, 145, 122],
 [376, 491, 208, 256, 141, 289, 196, 233, 307, 413, 579, 69, 119, 418, 145],
 [376, 491, 418, 256, 208, 141, 196, 233, 307, 413, 579, 69, 119, 145, 289],
 [69, 142, 491, 135, 141, 196, 233, 289, 307, 413, 579, 376, 208, 418, 145]]

In [28]:
# Get player points matrix for each week

# Weeks 1 - 11 has max 620 players.

for i in range(1,11):
    print(len(pd.read_csv("Players_Weekwise/week_"+str(i)+".csv")))

554
566
577
599
606
611
613
617
618
620


In [31]:
# Week 1 processing

# Get week 1 points of all players

df = pd.read_csv("Players_Weekwise/week_1.csv")
df = df[['id', 'stats.total_points']]
df = df.set_index('id')

In [32]:
df

stats.total_points
id                     
1                     1
2                     0
3                     0
4                     0
5                     0
..                  ...
550                   0
551                   0
552                   0
553                   0
554                   0

[554 rows x 1 columns]

In [42]:
# Get the total points of this FPL Manager in this week
total_points = df.loc[player_ids[0], :]['stats.total_points'].sum()

In [43]:
total_points

80

In [44]:
df.loc[player_ids[0], :]

stats.total_points
id                     
30                    2
275                   1
418                   1
237                   6
233                  17
215                   3
289                   8
485                   1
413                  13
337                   7
177                   7
376                   0
245                   6
208                   6
145                   2

In [65]:
# Replicate player scores horizontally len(df) times
scores_h = np.array([df.loc[player_ids[0], :]['stats.total_points'].to_numpy()])
scores_h

array([[ 2,  1,  1,  6, 17,  3,  8,  1, 13,  7,  7,  0,  6,  6,  2]])

In [66]:
import numpy as np
scores_h = np.repeat(scores_h, len(df), axis = 0)

In [62]:
# scores_h = scores_h.T

In [69]:
scores_h = scores_h.T

In [70]:
scores_h

array([[2, 2, 2, ..., 2, 2, 2],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [6, 6, 6, ..., 6, 6, 6],
       [6, 6, 6, ..., 6, 6, 6],
       [2, 2, 2, ..., 2, 2, 2]])

In [77]:
# Get all player_scores into matrix form.
ppoints = np.array([df['stats.total_points'].to_numpy()])
ppoints = np.repeat(ppoints, 15, axis=0)

In [78]:
ppoints

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [79]:
total_score = np.full((15,554), total_points)

In [80]:
total_score

array([[80, 80, 80, ..., 80, 80, 80],
       [80, 80, 80, ..., 80, 80, 80],
       [80, 80, 80, ..., 80, 80, 80],
       ...,
       [80, 80, 80, ..., 80, 80, 80],
       [80, 80, 80, ..., 80, 80, 80],
       [80, 80, 80, ..., 80, 80, 80]])

In [81]:
total_score.shape

(15, 554)

In [82]:
ppoints.shape

(15, 554)

In [83]:
scores_h.shape

(15, 554)

In [84]:
new_team_scores = total_score + ppoints - scores_h

In [85]:
new_team_scores

array([[79, 78, 78, ..., 78, 78, 78],
       [80, 79, 79, ..., 79, 79, 79],
       [80, 79, 79, ..., 79, 79, 79],
       ...,
       [75, 74, 74, ..., 74, 74, 74],
       [75, 74, 74, ..., 74, 74, 74],
       [79, 78, 78, ..., 78, 78, 78]])

In [86]:
# Row Number. Player swapped OUT.
np.argmax(np.max(new_team_scores, axis=1))

11

In [87]:
# Row Number. Player swapped IN.
np.argmax(np.max(new_team_scores, axis=0))

276

In [88]:
np.max(new_team_scores)

100

In [89]:
new_team_scores[11][276]

100

In [92]:
new_team_scores[11][0]

81

In [100]:
ppoints[11][276]

20

In [101]:
scores_h[11][276]

0

In [102]:
scores_h[11]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [105]:
player_id_swap_out = player_ids[0][11]
player_id_swap_out

376

In [106]:
player_id_swap_in = df.reset_index()['id'][276]
player_id_swap_in

277

In [115]:
# new_team = player_ids[0].append(player_id_swap_in)
# new_team.remove(player_id_swap_out)
# new_team
player_ids[0].extend([player_id_swap_in])
player_ids[0].remove(player_id_swap_out)


In [116]:
player_ids[0]

[30, 275, 418, 237, 233, 215, 289, 485, 413, 337, 177, 245, 208, 145, 277]

In [117]:
len(player_ids[0])

15

In [118]:
# New team after week 1
new_team = player_ids[0]
new_team

[30, 275, 418, 237, 233, 215, 289, 485, 413, 337, 177, 245, 208, 145, 277]

In [119]:
# New team score after week 1
new_score = new_team_scores[11][276]
new_score

100

In [ ]:
## Work In Progress(Cost) Begin

In [132]:
total_budget = r['entry_history']['bank']
total_budget

10

In [133]:
# Initialize budget matrix
budget_matrix = np.full((15, 554), total_budget)
budget_matrix


array([[10, 10, 10, ..., 10, 10, 10],
       [10, 10, 10, ..., 10, 10, 10],
       [10, 10, 10, ..., 10, 10, 10],
       ...,
       [10, 10, 10, ..., 10, 10, 10],
       [10, 10, 10, ..., 10, 10, 10],
       [10, 10, 10, ..., 10, 10, 10]])

In [141]:
# current_players_cost = 

r2 = requests.get('https://fantasy.premierleague.com/api/element-summary/1/').json()
r2


{'fixtures': [{'id': 114,
   'code': 2210384,
   'team_h': 11,
   'team_h_score': None,
   'team_a': 1,
   'team_a_score': None,
   'event': 12,
   'finished': False,
   'minutes': 0,
   'provisional_start_time': False,
   'kickoff_time': '2021-11-20T17:30:00Z',
   'event_name': 'Gameweek 12',
   'is_home': False,
   'difficulty': 5},
  {'id': 121,
   'code': 2210391,
   'team_h': 1,
   'team_h_score': None,
   'team_a': 14,
   'team_a_score': None,
   'event': 13,
   'finished': False,
   'minutes': 0,
   'provisional_start_time': False,
   'kickoff_time': '2021-11-27T12:30:00Z',
   'event_name': 'Gameweek 13',
   'is_home': True,
   'difficulty': 2},
  {'id': 134,
   'code': 2210404,
   'team_h': 13,
   'team_h_score': None,
   'team_a': 1,
   'team_a_score': None,
   'event': 14,
   'finished': False,
   'minutes': 0,
   'provisional_start_time': False,
   'kickoff_time': '2021-12-02T20:15:00Z',
   'event_name': 'Gameweek 14',
   'is_home': False,
   'difficulty': 4},
  {'id': 142,


In [139]:
# base url for all FPL API endpoints
base_url = 'https://fantasy.premierleague.com/api/'

# get data from bootstrap-static endpoint
r1 = requests.get(base_url+'bootstrap-static/').json()

# show the top level fields
pprint(r1, indent=2, depth=1, compact=True)

{ 'element_stats': [...],
  'element_types': [...],
  'elements': [...],
  'events': [...],
  'game_settings': {...},
  'phases': [...],
  'teams': [...],
  'total_players': 8598389}


In [140]:
r1['elements']

[{'chance_of_playing_next_round': None,
  'chance_of_playing_this_round': None,
  'code': 80201,
  'cost_change_event': -1,
  'cost_change_event_fall': 1,
  'cost_change_start': -4,
  'cost_change_start_fall': 4,
  'dreamteam_count': 0,
  'element_type': 1,
  'ep_next': '-0.5',
  'ep_this': '1.0',
  'event_points': 0,
  'first_name': 'Bernd',
  'form': '0.0',
  'id': 1,
  'in_dreamteam': False,
  'news': '',
  'news_added': None,
  'now_cost': 46,
  'photo': '80201.jpg',
  'points_per_game': '1.3',
  'second_name': 'Leno',
  'selected_by_percent': '1.0',
  'special': False,
  'squad_number': None,
  'status': 'a',
  'team': 1,
  'team_code': 3,
  'total_points': 4,
  'transfers_in': 58195,
  'transfers_in_event': 343,
  'transfers_out': 166115,
  'transfers_out_event': 1079,
  'value_form': '0.0',
  'value_season': '0.9',
  'web_name': 'Leno',
  'minutes': 270,
  'goals_scored': 0,
  'assists': 0,
  'clean_sheets': 0,
  'goals_conceded': 9,
  'own_goals': 0,
  'penalties_saved': 0,
  '

In [142]:
### WIP End

In [151]:
### COST PART BEGIN
# Randomly CROSS OUT some transfers

random_cost = np.random.choice([0,1],(15, 554), p=[0.5, 0.5])

In [152]:
random_cost

array([[0, 1, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 1, 1, ..., 1, 1, 0]])

In [153]:
new_score_with_cost = np.multiply(random_cost, new_team_scores)
new_score_with_cost

array([[ 0, 78, 78, ..., 78, 78,  0],
       [ 0,  0, 79, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0, 79, 79],
       ...,
       [ 0, 74,  0, ..., 74, 74,  0],
       [75,  0,  0, ..., 74,  0,  0],
       [ 0, 78, 78, ..., 78, 78,  0]])

In [154]:
# Row Number. Player swapped OUT.
np.argmax(np.max(new_score_with_cost, axis=1))

7

In [155]:
# Row Number. Player swapped IN.
np.argmax(np.max(new_score_with_cost, axis=0))

276

In [156]:
np.max(new_score_with_cost)

99

In [157]:
player_id_swap_out = player_ids[0][11]
player_id_swap_out

245

In [158]:
player_id_swap_in = df.reset_index()['id'][276]
player_id_swap_in

277

In [160]:
new_team_after_swap = player_ids[0]
new_team_after_swap.extend([player_id_swap_in])
new_team_after_swap.remove(player_id_swap_out)
new_team_after_swap

[30, 275, 418, 237, 233, 215, 289, 485, 413, 337, 177, 376, 208, 145, 277]

In [161]:
len(new_team_after_swap)

15

In [228]:
np.random.seed(0)
# For each FPL Manager

fpl_manager_id = '2757'

# Get the players picked by a FPL Manager in week 1
# player_ids = []
r = requests.get('https://fantasy.premierleague.com/api/entry/'+fpl_manager_id+'/event/1/picks/').json()
player_ids = [x['element'] for x in r['picks']]

player_ids

scores_each_week = []
team_each_week = []

#Initialise total team points
df_tmp = pd.read_csv("Players_Weekwise/week_1.csv")
df_tmp = df_tmp[['id', 'stats.total_points']]
df_tmp = df_tmp.set_index('id')
total_points = df_tmp.loc[player_ids, :]['stats.total_points'].sum()

scores_each_week.append(total_points)
team_each_week.append(player_ids)

for week in range(2,8):
    # Get number of players in that week available for swap
    df = pd.read_csv("Players_Weekwise/week_"+str(week)+".csv")
    df = df[['id', 'stats.total_points']]
    df = df.set_index('id')
    # print(df)
    
#     total_points = df.loc[player_ids, :]['stats.total_points'].sum()
        
    print("Total Points "+str(total_points))
    # Replicate player scores horizontally len(df) times
    scores_h = np.array([df.loc[player_ids, :]['stats.total_points'].to_numpy()])
    scores_h = np.repeat(scores_h, len(df), axis = 0)
    scores_h = scores_h.T
#     print(scores_h)
    
    # Get all player_scores into matrix form.
    ppoints = np.array([df['stats.total_points'].to_numpy()])
    ppoints = np.repeat(ppoints, 15, axis=0)
    
    #Create total score matrix
    total_score = np.full((15,len(df)), total_points)
    
    #Create transfers/swaps to get new scores
    new_team_scores = total_score + ppoints - scores_h
#     print(new_team_scores)
    
    # Randomly CROSS OUT some transfers based on some cost
    random_cost = np.random.choice([0,1],(15, len(df)), p=[0.5, 0.5])
    new_score_with_cost = np.multiply(random_cost, new_team_scores)
#     print(new_score_with_cost)
    # Row Number. Player swapped OUT.
#     print(np.argmax(np.max(new_score_with_cost, axis=1)))
    # Row Number. Player swapped IN.
#     print(np.argmax(np.max(new_score_with_cost, axis=0)))
    
#     print(np.max(new_score_with_cost))
    
    print("Swap OUT")
    player_id_swap_out = player_ids[np.argmax(np.max(new_score_with_cost, axis=1))]
    print(df.loc[player_id_swap_out]['stats.total_points'])
#     print(player_id_swap_out)
    
#     print(scores_h[np.argmax(np.max(new_score_with_cost, axis=1))])
    
    print("Swap IN")
    player_id_swap_in = df.reset_index()['id'][np.argmax(np.max(new_score_with_cost, axis=0))]
#     print(player_id_swap_in)
    print(df.loc[player_id_swap_in]['stats.total_points'])
#     print(ppoints[0][np.argmax(np.max(new_score_with_cost, axis=0))])
    
    player_ids.extend([player_id_swap_in])
    player_ids.remove(player_id_swap_out)
    print("New Points "+ str(np.max(new_score_with_cost)))
    scores_each_week.append(np.max(new_score_with_cost))
    new_player_ids = player_ids
    team_each_week.append(new_player_ids)
    total_points = np.max(new_score_with_cost)
    print(new_player_ids)

Total Points 80
Swap OUT
0
Swap IN
18
New Points 98
[30, 275, 418, 237, 233, 215, 289, 485, 413, 337, 177, 245, 208, 145, 142]
Total Points 98
Swap OUT
1
Swap IN
18
New Points 115
[30, 275, 237, 233, 215, 289, 485, 413, 337, 177, 245, 208, 145, 142, 268]
Total Points 115
Swap OUT
-1
Swap IN
13
New Points 129
[30, 275, 237, 233, 215, 289, 485, 337, 177, 245, 208, 145, 142, 268, 125]
Total Points 129
Swap OUT
0
Swap IN
15
New Points 144
[30, 275, 233, 215, 289, 485, 337, 177, 245, 208, 145, 142, 268, 125, 44]
Total Points 144
Swap OUT
0
Swap IN
15
New Points 159
[30, 233, 215, 289, 485, 337, 177, 245, 208, 145, 142, 268, 125, 44, 36]
Total Points 159
Swap OUT
0
Swap IN
15
New Points 174
[30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190]


In [229]:
scores_each_week

[80, 98, 115, 129, 144, 159, 174]

In [230]:
team_each_week

[[30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190],
 [30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190],
 [30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190],
 [30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190],
 [30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190],
 [30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190],
 [30, 233, 215, 289, 485, 337, 245, 208, 145, 142, 268, 125, 44, 36, 190]]

In [231]:
# Actual points of FPL Manager

actual_points = []
running_total = 0

r = requests.get('https://fantasy.premierleague.com/api/entry/'+fpl_manager_id+'/event/1/picks/').json()
player_ids = [x['element'] for x in r['picks']]
df = pd.read_csv("Players_Weekwise/week_1.csv")
df = df[['id', 'stats.total_points']]
df = df.set_index('id')
running_total += df.loc[player_ids, :]['stats.total_points'].sum()
actual_points.append(running_total)

for week in range(2,8):
    r = requests.get('https://fantasy.premierleague.com/api/entry/'+fpl_manager_id+'/event/'+str(week)+'/picks/').json()
    player_ids = [x['element'] for x in r['picks']]
    df = pd.read_csv("Players_Weekwise/week_"+str(week)+".csv")
    df = df[['id', 'stats.total_points']]
    df = df.set_index('id')
    running_total += df.loc[player_ids, :]['stats.total_points'].sum()
    actual_points.append(running_total)
actual_points

[80, 166, 238, 297, 355, 401, 436]